version: '2'
services:
    keken-app:
        image: keken
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://keken-mysql:3306/keken?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=keken-elasticsearch:9300
        ports:
            - 8080:8080
    keken-mysql:
        extends:
            file: mysql.yml
            service: keken-mysql
    keken-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: keken-elasticsearch
